In [1]:
import numpy as np

In [2]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [3]:
    np.zeros((2,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [4]:
a = np.ones((4,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
np.full_like(a,12)

array([[12., 12., 12., 12.],
       [12., 12., 12., 12.],
       [12., 12., 12., 12.],
       [12., 12., 12., 12.]])

In [6]:
np.full(a.shape, 10)

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [7]:
rr = np.full(a.shape,20, dtype = 'int8')

In [8]:
rr.dtype

dtype('int8')

In [9]:
out = np.ones((5,5))
print(out)
print('-------------------------------------------')
z = np.zeros((3,3))
print(z)
print('-------------------------------------------')
z[1:2,1:2] = 9
print(z)
print('-------------------------------------------')

out[1:4,1:4] = z
print(out)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
-------------------------------------------
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
-------------------------------------------
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
-------------------------------------------
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [10]:
aa = np.array([2,1,3,4])
aa

array([2, 1, 3, 4])

In [11]:
b = aa.copy()
b[1]=200
print(b)
print(aa)

[  2 200   3   4]
[2 1 3 4]


In [12]:
np.vstack()
np.hstack()

TypeError: _vhstack_dispatcher() missing 1 required positional argument: 'tup'

In [14]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
cc = [1,2,3,4,5,6,7,8,9]
arr = np.array(cc)

In [16]:
nn = arr.reshape(3,3)
nn

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
output = {'Mean':[nn.mean(axis=0).tolist(),nn.mean(axis=1).tolist(),arr.std(axis=0).tolist()]}
output

{'Mean': [[4.0, 5.0, 6.0], [2.0, 5.0, 8.0], 2.581988897471611]}

In [26]:
nn.std()

2.581988897471611

In [18]:
nn.mean(axis=0).tolist()

[4.0, 5.0, 6.0]

In [35]:
re = [2345843897,3489,345,456,7567,56345,346,546,56756,768,34]
reg = np.array(re)

In [36]:
reg

array([2345843897,       3489,        345,        456,       7567,
            56345,        346,        546,      56756,        768,
               34], dtype=int64)

In [37]:
man = reg

In [46]:
man = man.reshape(-1,1)

In [47]:
man

array([[2345843897],
       [      3489],
       [       345],
       [       456],
       [      7567],
       [     56345],
       [       346],
       [       546],
       [     56756],
       [       768],
       [        34]], dtype=int64)

In [48]:
reg

array([2345843897,       3489,        345,        456,       7567,
            56345,        346,        546,      56756,        768,
               34], dtype=int64)

In [1]:
txt =[ "10.2.23.323 - car [2022:13:5] this is it ", "10.2.23.323 - car [2022:13:5] this is it ", "10.2.23.323 - car [2022:13:5] this is it "] 

In [22]:
def parser1():
    for line in txt:
        print(re.split("\[|\]", line)[1])

In [28]:
nums = [-3,-5,-1,3,5,7,8]
def sqsum(nums):
    return sum(x**2 for x in nums if x>0)

In [29]:
sqsum(nums)

147

In [33]:
nums=[23,34]
nums=[33]

In [41]:
class newnums:
    pass
nums = newnums()

In [42]:
nums.name = "Reuben Solomon "